name: CI
 
on: 
  pull_request: 
  push:
    branches: 
      - main

jobs: 
  build-and-test: 
    runs-on: ubuntu-lastest
    steps: 
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci 

      - name: Decode service account key
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" | base64 -d > ./src/firebase/serviceAccountKey.json

      - name: build
        run: npm run build

